# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "rake"

  gem "rspec"

  gem "rubocop-rspec"

  gem "rubocop", "~> 1.36"

  gem "yard", "~> 0.9.28"

  gem "webmock", "~> 3.13"

  gem "openapi3_parser", "~> 0.9.2"

  platforms :mri do
    gem "byebug"
    gem "pry"
    gem "pry-byebug"
  end
end
