version: 2
updates:
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: daily
    commit-message:
      prefix: "Ruby"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "ruby"
      - "dependencies"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "JS"
      include: "scope"
    labels:
      - "js"
      - "dependencies"

  - package-ecosystem: npm
    directory: "/alexandria"
    schedule:
      interval: daily
    commit-message:
      prefix: "JS"
      include: "scope"
    labels:
      - "js"
      - "dependencies"
