name: Release Ruby

on:
  push:
    tags:
      - '*.*.*'
jobs:
  publish:
    name: Release to RubyGems
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        timeout-minutes: 10
        with:
          ref: 'refs/heads/main'
          running-workflow-name: 'Release to RubyGems'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - uses: actions/checkout@v3

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          WORKDIR: ruby
          RELEASE_COMMAND: rake release
